 <ul class="breadcrumb">
  <li><a href="<?php echo $this->url(array('action'=>'index', 'controller'=>'index'))?>">Home</a> <span class="divider">/</span></li>
  <li class="active">Guestbook</li>
</ul>

<a class="btn" href="<?php echo $this->url( array( 'controller' => 'guestbook', 'action' => 'sign' ), 'default', true) ?>">Sign</a>
     <table class="zebra-striped" id="sortTableExample">
        <thead>
          <tr>
            <th>#</th>
            <th class="yellow">Email</th>
            <th class="blue">Comment</th>
            <th class="green">Created At</th>
          </tr>
        </thead>
        <tbody> <?php foreach ($this->guestbook_paginator as $guestbook): ?>
          <tr>
            <td><?php echo $this->escape($guestbook->id) ?></td>
            <td><?php echo $this->escape($guestbook->email) ?></td>
            <td><?php echo $this->escape($guestbook->comment) ?></td>
            <td><?php echo $this->escape($guestbook->created) ?></td>
          </tr><?php endforeach ?>
        </tbody>
      </table>
<?php echo $this->guestbook_paginator;?>




