<?php if ($this->pageCount): ?>
<div class="pagination"> <ul>
<!-- Previous page link -->
<?php if ($this->first<$this->firstPageInRange): ?>
   <li class="first"><a href="<?php echo $this->url(array('page' => $this->first)); ?>">
    &lt;&lt; First
  </a> </li>
<?php endif; ?>
<?php if (isset($this->previous)): ?>
   <li class="prev"><a href="<?php echo $this->url(array('page' => $this->previous)); ?>">
    &lt; Previous
  </a> </li>
<?php endif; ?>

<!-- Numbered page links -->
<?php foreach ($this->pagesInRange as $page): ?>
  <?php if ($page != $this->current): ?>
     <li><a href="<?php echo $this->url(array('page' => $page)); ?>">
        <?php echo $page; ?>
    </a> </li>
  <?php else: ?>
  <li class="active"><a href="#"><?php echo $page; ?></a></li>
  <?php endif; ?>
<?php endforeach; ?>

<!-- Next page link -->
<?php if (isset($this->next)): ?>
   <li><a class="next" href="<?php echo $this->url(array('page' => $this->next)); ?>">
    Next &gt;
  </a></li>
<?php endif; ?>
<?php if ($this->last>$this->lastPageInRange): ?>
   <li><a class="last" href="<?php echo $this->url(array('page' => $this->last)); ?>">
    Last &gt;&gt;
  </a></li>
<?php endif; ?>
</ul>
</div>
<?php endif; ?>