<div class="well">
  <h5>Guestbook</h5>
  <ul>
    <li><a href="<?php echo $this->url(array('action'=>'index', 'controller'=>'guestbook'))?>">List</a></li>
    <li><a href="<?php echo $this->url(array('action'=>'create', 'controller'=>'guestbook'))?>">Create</a></li>
    <li><a href="#">Link</a></li>
    <li><a href="#">Link</a></li>
    <li><a href="#">Link</a></li>
  </ul>
  <h5>Destinations & Routines</h5>
  <ul>
    <li><a href="#">Link</a></li>
    <li><a href="#">Link</a></li>
    <li><a href="#">Link</a></li>
    <li><a href="#">Link</a></li>
    <li><a href="#">Link</a></li>
    <li><a href="#">Link</a></li>
  </ul>
  <h5>Orders</h5>
  <ul>
    <li><a href="#">Link</a></li>
    <li><a href="#">Link</a></li>
  </ul>
  <h5>Misc</h5>
  <ul>
    <?php include(dirname(__file__). '/auto.phtml');?>
  </ul>
</div>