<?php echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <title>Zend Framework Quickstart Application</title>
  <?php echo $this->headLink()->appendStylesheet('/assets/css/global.css') ?>
</head>
<body>
<div id="header" style="background-color: #EEEEEE; height: 30px;">
    <div id="header-logo" style="float: left">
        <b>ZF Quickstart Application</b>
    </div>
    <div id="header-navigation" style="float: right">
        <a href="<?php echo $this->url(
            array('controller'=>'guestbook'),
            'default',
            true) ?>">Guestbook</a>
    </div>
</div>
<?php foreach($this->messages as $message):?>
<div class="alert-message <?php echo $message['lvl'] ?>">
  <a class="close" href="#">×</a>
  <p><?php echo $message['message'] ?></p>
</div>
<?php endforeach;?>
<?php echo $this->layout()->content ?>
 <?php echo $this->jQuery();?>
</body>
</html>