 <a class="btn" href="[?php echo $this->url( array('action' => 'create' ), 'default') ?]">[?php echo $this->translate('Create')?]</a>
 <a class="btn" href="[?php echo $this->url( array('action' => 'populate' ), 'default') ?]">[?php echo $this->translate('Populate')?]</a>

 <table class="zebra-striped">
    <thead>
      <tr>
        <th>#</th>
        <?php foreach($columns as $column):?>
        <?php if($column['PRIMARY'])continue;?>
        <?php if($column['DATA_TYPE']=='text')continue;?>

        <th class="blue">[?php echo $this->translate('lbl_<?php echo $cls;?>_<?php echo $column['COLUMN_NAME'];?>')?]</th>
        <?php endforeach;?>

        <th class="green">[?php echo $this->translate('Actions')?]</th>
      </tr>
    </thead>
    <tbody>[?php foreach ($this-><?php echo $table_name;?>_paginator as $<?php echo $table_name;?>): ?]
      <tr>
        <td>[?php echo $this->escape($<?php echo $table_name;?>->id) ?]</td>
        <?php foreach($columns as $column):?>
        <?php if($column['PRIMARY'])continue;?>
        <?php if($column['DATA_TYPE']=='text')continue;?>

        <td>[?php echo $this->escape($<?php echo $table_name;?>-><?php echo $column['COLUMN_NAME'];?>) ?]</td><?php endforeach;?>
        <td>
        <a href="[?php echo $this->url( array( 'action' => 'view', 'id'=>$<?php echo $table_name;?>->id)) ?]">[?php echo $this->translate('View')?]</a>
        <a href="[?php echo $this->url( array( 'action' => 'edit', 'id'=>$<?php echo $table_name;?>->id)) ?]">[?php echo $this->translate('Edit')?]</a>
        <a href="[?php echo $this->url( array( 'action' => 'delete', 'id'=>$<?php echo $table_name;?>->id)) ?]">[?php echo $this->translate('Delete')?]</a>
        </td>
      </tr>[?php endforeach ?]
    </tbody>
  </table>
[?php echo $this-><?php echo $table_name;?>_paginator;?]