 <ul class="breadcrumb">
  <li><a href="<?php echo $this->url(array('action'=>'index', 'controller'=>'index'))?>">Home</a> <span class="divider">/</span></li>
  <li class="active">Guestbook</li>
</ul>


<a href="<?php echo $this->url( array('filter_confirm' => 'all' ), 'default') ?>"<?php $this->filter_confirm=='all' and print ' class="active"' ?>>All</a>
<a href="<?php echo $this->url( array('filter_confirm' => 'confirmed' ), 'default') ?>"<?php $this->filter_confirm=='confirmed' and print ' class="active"' ?>>confirmed</a>
<a href="<?php echo $this->url( array('filter_confirm' => 'unconfirmed' ), 'default') ?>"<?php $this->filter_confirm=='unconfirmed' and print ' class="active"' ?>>unconfirmed</a>

     <a class="btn" href="<?php echo $this->url( array('action' => 'create' ), 'default') ?>">Create</a>
     <a class="btn" href="<?php echo $this->url( array('action' => 'populate' ), 'default') ?>">Populate</a>

     <table class="zebra-striped">
        <thead>
          <tr>
            <th>#</th>
            <th class="yellow">Email</th>
            <th class="blue">Comment</th>
            <th class="green">Created At</th>
            <th class="green">Status</th>
            <th class="green">Actions</th>
          </tr>
        </thead>
        <tbody> <?php foreach ($this->guestbook_paginator as $guestbook): ?>
          <tr>
            <td><?php echo $this->escape($guestbook->id) ?></td>
            <td><?php echo $this->gravatar($guestbook->email);?><?php echo $this->escape($guestbook->email) ?></td>
            <td><?php echo $this->escape($guestbook->comment) ?></td>
            <td><?php echo $this->escape($guestbook->created) ?></td>
            <td>
            <?php if($guestbook->isConfirmed()): ?>
            <?php echo $this->escape($guestbook->confirmed) ?>
            <?php else: ?>
            <a href="<?php echo $this->url( array( 'action' => 'confirm', 'id'=>$guestbook->id)) ?>">Confirm</a>
            <?php endif; ?>
            </td>
            <td>
            <a href="<?php echo $this->url( array( 'action' => 'edit', 'id'=>$guestbook->id)) ?>">Edit</a>
            <a href="<?php echo $this->url( array( 'action' => 'delete', 'id'=>$guestbook->id)) ?>">Delete</a>
            </td>
          </tr><?php endforeach ?>
        </tbody>
      </table>
<?php echo $this->guestbook_paginator;?>




